### ISSUE TITLE
Timeouts during CONNECT

### ISSUE THREAD

**Issue by mitchbear** [Niravk1997/HP-3478A-Software#1]
I was finding that i was consistently getting COM port timeouts during the CONNECT sequence, no matter what I set the timeout to, and independent of whether I built the code for DEBUG or RELEASE.  I found that if I return "true" from the verification exception routines, ignoring the timeout, I was able to connect consistently without impacting functionality.  This might be due to the fact that I'm using AR488 on an Arduino UNO or an older laptop.  I have not traced down what the root cause of the timeouts are... I tried putting more delay between sending and receiving commands without it fixing the problem.

**Comment by Niravk1997** [comment]
All my software are tested and build for the Arduino Pro Micro version. I don't have an Arduino Uno so I can't really test the software for it. I think the pro micro simulates the serial connection as it has built-in support for USB, no external serial chip required.
Try to set request to send to false and see what happens. 
My guess is that its the adapter not the computer. I just tested it, haven't used the meter in a while, no timeout issues.
![Capture](https://user-images.githubusercontent.com/52579388/146806002-09f2e67d-47d3-48e0-b00b-3b4025a367eb.JPG)

**Comment by mitchbear** [comment]
Setting the "Request to Send" to FALSE did not solve the issue.  

In the debugger, I believe there are two issues:  One is that my 3478A often sends 10 characters back instead of 11 (omitting the plus sign - sometimes it sends 4 characters when it is exactly at 0.0)  But bypassing that check, I still get the timeouts, no matter whether "Request to Send" is true or false.  Personally, I am fine - I have modified my software to omit the checks, and it works well for me.  Perhaps an option to "omit verification checks" in the CONNECT screen would allow variants of this meter to work, and overcome these types of issues - there wouldn't be much downside.  

Keep up the great work!

- Mitch

**Comment by Niravk1997** [comment]
Thanks for letting me know. All my 3478A meters return values with 11 characters no matter what, this is why I added the 11 character verification check. The verification check prevents the software from processing corrupted measurement data. This was case with my old computer where sometimes the measurement data would be missing few characters like the Scientific notation character 'E' so instead of +1.00000E+2 it would be +1.00000+2. I will add an option to disable the verification check when I decide to update this software.
![Capture](https://user-images.githubusercontent.com/52579388/146813953-f3cc499c-6f99-4917-af26-4f96d907969e.JPG)
